Repository HotcakesCommerce/hotcakes-commerce-core, pull requests merged in 2020-10, with the labels that each got.

#318 Bug Fix for API timeout
  DevSamples/MyViewSet/Portals/_default/HotcakesViews/MyBootstrap4/Scripts/Checkout.js
  DevSamples/MyViewSet/Portals/_default/HotcakesViews/MyBootstrap4/Views/Checkout/_Login.cshtml
  DevSamples/MyViewSet/Portals/_default/HotcakesViews/MyLegacy/Scripts/Checkout.js
  DevSamples/MyViewSet/Portals/_default/HotcakesViews/MyLegacy/Views/Checkout/_Login.cshtml
  DevSamples/MyViewSet/Portals/_default/HotcakesViews/MyViewSet/Scripts/Checkout.js
  DevSamples/MyViewSet/Portals/_default/HotcakesViews/MyViewSet/Views/Checkout/_Login.cshtml
  DevSamples/MyViewSet/Portals/_default/HotcakesViews/Porto5/Scripts/Checkout.js
  DevSamples/MyViewSet/Portals/_default/HotcakesViews/Porto5/Views/Checkout/_Login.cshtml
  DevSamples/MyViewSet/Portals/_default/HotcakesViews/Scripts/Checkout.js
  DevSamples/MyViewSet/Portals/_default/HotcakesViews/SocialSpokes/Scripts/Checkout.js
  DevSamples/MyViewSet/Portals/_default/HotcakesViews/SocialSpokes/Views/Checkout/_Login.cshtml
  DevSamples/MyViewSet/Portals/_default/HotcakesViews/Views/Checkout/_Login.cshtml
  Website/DesktopModules/Hotcakes/Core/Controllers/CheckoutController.cs
  Website/Portals/_default/HotcakesViews/Bootstrap4/Scripts/Checkout.js
  Website/Portals/_default/HotcakesViews/Bootstrap4/Views/Checkout/_Login.cshtml
  Website/Portals/_default/HotcakesViews/Porto5/Scripts/Checkout.js
  Website/Portals/_default/HotcakesViews/Porto5/Views/Checkout/_Login.cshtml
  Website/Portals/_default/HotcakesViews/SocialSpokes/Scripts/Checkout.js
  Website/Portals/_default/HotcakesViews/SocialSpokes/Views/Checkout/_Login.cshtml
  Website/Portals/_default/HotcakesViews/_default-Legacy/Scripts/Checkout.js
  Website/Portals/_default/HotcakesViews/_default-Legacy/Views/Checkout/_Login.cshtml
  Website/Portals/_default/HotcakesViews/_default/Scripts/Checkout.js
  Website/Portals/_default/HotcakesViews/_default/Views/Checkout/_Login.cshtml
Labels: bug

#317 Fixed bug in Viewsets
  DevSamples/MyViewSet/Portals/_default/HotcakesViews/MyBootstrap4/Scripts/Checkout.js
  DevSamples/MyViewSet/Portals/_default/HotcakesViews/MyBootstrap4/Scripts/aes.js
  DevSamples/MyViewSet/Portals/_default/HotcakesViews/MyBootstrap4/Views/Checkout/_CreditCardInput.cshtml
  DevSamples/MyViewSet/Portals/_default/HotcakesViews/MyLegacy/Scripts/Checkout.js
  DevSamples/MyViewSet/Portals/_default/HotcakesViews/MyLegacy/Scripts/aes.js
  DevSamples/MyViewSet/Portals/_default/HotcakesViews/MyLegacy/Views/Checkout/_CreditCardInput.cshtml
  DevSamples/MyViewSet/Portals/_default/HotcakesViews/MyViewSet/Scripts/Checkout.js
  DevSamples/MyViewSet/Portals/_default/HotcakesViews/MyViewSet/Scripts/aes.js
  DevSamples/MyViewSet/Portals/_default/HotcakesViews/MyViewSet/Views/Checkout/_CreditCardInput.cshtml
  DevSamples/MyViewSet/Portals/_default/HotcakesViews/Porto5/Scripts/Checkout.js
  DevSamples/MyViewSet/Portals/_default/HotcakesViews/Porto5/Scripts/aes.js
  DevSamples/MyViewSet/Portals/_default/HotcakesViews/Porto5/Views/Checkout/_CreditCardInput.cshtml
  DevSamples/MyViewSet/Portals/_default/HotcakesViews/Scripts/Checkout.js
  DevSamples/MyViewSet/Portals/_default/HotcakesViews/Scripts/aes.js
  DevSamples/MyViewSet/Portals/_default/HotcakesViews/SocialSpokes/Scripts/Checkout.js
  DevSamples/MyViewSet/Portals/_default/HotcakesViews/SocialSpokes/Scripts/aes.js
  DevSamples/MyViewSet/Portals/_default/HotcakesViews/SocialSpokes/Views/Checkout/_CreditCardInput.cshtml
  DevSamples/MyViewSet/Portals/_default/HotcakesViews/Views/Checkout/_CreditCardInput.cshtml
  Libraries/Hotcakes.Commerce/Common/Constants.cs
  Website/DesktopModules/Hotcakes/03.05.00.txt
  Website/DesktopModules/Hotcakes/Checkout/CheckoutView.ascx.cs
  Website/DesktopModules/Hotcakes/Core/Controllers/CheckoutController.cs
  Website/DesktopModules/Hotcakes/Core/Models/CheckoutViewModel.cs
  Website/DesktopModules/Hotcakes/Hotcakes.Modules.csproj
  Website/DesktopModules/Hotcakes/Hotcakes.dnn
  Website/DesktopModules/Hotcakes/Providers/DataProviders/SqlDataProvider/03.05.00.SqlDataProvider
  Website/Portals/_default/HotcakesViews/Bootstrap4/Scripts/Checkout.js
  Website/Portals/_default/HotcakesViews/Bootstrap4/Scripts/aes.js
  Website/Portals/_default/HotcakesViews/Bootstrap4/Views/Checkout/_CreditCardInput.cshtml
  Website/Portals/_default/HotcakesViews/Porto5/Scripts/Checkout.js
  Website/Portals/_default/HotcakesViews/Porto5/Scripts/aes.js
  Website/Portals/_default/HotcakesViews/Porto5/Views/Checkout/_CreditCardInput.cshtml
  Website/Portals/_default/HotcakesViews/SocialSpokes/Scripts/Checkout.js
  Website/Portals/_default/HotcakesViews/SocialSpokes/Scripts/aes.js
  Website/Portals/_default/HotcakesViews/SocialSpokes/Views/Checkout/_CreditCardInput.cshtml
  Website/Portals/_default/HotcakesViews/_default-Legacy/Scripts/Checkout.js
  Website/Portals/_default/HotcakesViews/_default-Legacy/Scripts/aes.js
  Website/Portals/_default/HotcakesViews/_default-Legacy/Views/Checkout/_CreditCardInput.cshtml
  Website/Portals/_default/HotcakesViews/_default/Scripts/Checkout.js
  Website/Portals/_default/HotcakesViews/_default/Scripts/aes.js
  Website/Portals/_default/HotcakesViews/_default/Views/Checkout/_CreditCardInput.cshtml
Labels: bug

#309 Adding support for submit type button elements to forms
  Website/DesktopModules/Hotcakes/Core/Scripts/hcc.views.js
  Website/DesktopModules/Hotcakes/Core/Scripts/hcc.views.min.js
Labels: enhancement

#325 Issues/issue 311
  Website/DesktopModules/Hotcakes/Core/Controllers/ProductsController.cs
  Website/DesktopModules/Hotcakes/Core/Models/ProductPageViewModel.cs
  Website/bin/Dnn.PersonaBar.Library.dll
Labels: enhancement

#335 Updating DevSamples references
  DevSamples/References/Hotcakes.Commerce.Dnn.pdb
  DevSamples/References/Hotcakes.Commerce.dll
  DevSamples/References/Hotcakes.CommerceDTO.dll
  DevSamples/References/Hotcakes.Modules.dll
  DevSamples/References/Hotcakes.Payment.dll
  DevSamples/References/Hotcakes.Web.dll
Labels: Task

#338 Updated DLLs
  CommonAssemblyInfo.cs
  DevSamples/References/Hotcakes.Commerce.Dnn.dll
  DevSamples/References/Hotcakes.Commerce.dll
  DevSamples/References/Hotcakes.CommerceDTO.dll
  DevSamples/References/Hotcakes.Modules.dll
  DevSamples/References/Hotcakes.Payment.dll
  DevSamples/References/Hotcakes.Web.dll
  References/Misc/ReadMe.txt
  References/Misc/Stripe.net.dll
  References/Misc/Stripe.net.pdb
  References/Misc/stripe.net-5.0.0/src/.nuget/NuGet.exe
  References/Misc/stripe.net-5.0.0/src/Stripe.Tests/App.config
  References/Misc/stripe.net-5.0.0/src/Stripe.Tests/Stripe.Tests.csproj
  References/Misc/stripe.net-5.0.0/src/Stripe.Tests/packages.config
  References/Misc/stripe.net-5.0.0/src/Stripe/Stripe.csproj
  References/Misc/stripe.net-5.0.0/src/Stripe/packages.config
  Website/DesktopModules/Hotcakes/bin/Stripe.net.dll
  Website/DesktopModules/Hotcakes/bin/Stripe.net.pdb
Labels: Task
