Repository HotcakesCommerce/hotcakes-commerce-core, pull requests merged in 2021-12, with the labels that each got.

#359 Fix #292 - Affiliate & Category (drilldown) views don't work
  DevSamples/MyViewSet/Portals/_default/HotcakesViews/MyBootstrap4/Views/AffiliateRegistration/App_LocalResources/Index.cshtml.resx
  DevSamples/MyViewSet/Portals/_default/HotcakesViews/MyBootstrap4/Views/AffiliateRegistration/Index.cshtml
  DevSamples/MyViewSet/Portals/_default/HotcakesViews/MyLegacy/Views/AffiliateRegistration/App_LocalResources/Index.cshtml.resx
  DevSamples/MyViewSet/Portals/_default/HotcakesViews/MyLegacy/Views/AffiliateRegistration/Index.cshtml
  DevSamples/MyViewSet/Portals/_default/HotcakesViews/MyViewSet/Views/AffiliateRegistration/Index.cshtml
  DevSamples/MyViewSet/Portals/_default/HotcakesViews/Porto5/Views/AffiliateRegistration/App_LocalResources/Index.cshtml.resx
  DevSamples/MyViewSet/Portals/_default/HotcakesViews/Porto5/Views/AffiliateRegistration/Index.cshtml
  DevSamples/MyViewSet/Portals/_default/HotcakesViews/SocialSpokes/Views/AffiliateRegistration/App_LocalResources/Index.cshtml.resx
  DevSamples/MyViewSet/Portals/_default/HotcakesViews/SocialSpokes/Views/AffiliateRegistration/Index.cshtml
  Libraries/Hotcakes.Shipping/USPSAddressProvider.cs
  Website/DesktopModules/Hotcakes/Core/Models/AffiliateViewModel.cs
  Website/Portals/_default/HotcakesViews/Bootstrap4/Views/AffiliateRegistration/App_LocalResources/Index.cshtml.resx
  Website/Portals/_default/HotcakesViews/Bootstrap4/Views/AffiliateRegistration/Index.cshtml
  Website/Portals/_default/HotcakesViews/Porto5/Views/AffiliateRegistration/App_LocalResources/Index.cshtml.resx
  Website/Portals/_default/HotcakesViews/Porto5/Views/AffiliateRegistration/Index.cshtml
  Website/Portals/_default/HotcakesViews/SocialSpokes/Views/AffiliateRegistration/App_LocalResources/Index.cshtml.resx
  Website/Portals/_default/HotcakesViews/SocialSpokes/Views/AffiliateRegistration/Index.cshtml
  Website/Portals/_default/HotcakesViews/_default-Legacy/Views/AffiliateRegistration/App_LocalResources/Index.cshtml.resx
  Website/Portals/_default/HotcakesViews/_default-Legacy/Views/AffiliateRegistration/Index.cshtml
  Website/Portals/_default/HotcakesViews/_default/Views/AffiliateRegistration/App_LocalResources/Index.cshtml.resx
  Website/Portals/_default/HotcakesViews/_default/Views/AffiliateRegistration/Index.cshtml
Labels: bug

#380 Exclude plUpload and FileUpload
  Website/DesktopModules/Hotcakes/03.06.00.txt
  Website/DesktopModules/Hotcakes/Core/FileUpload.ashx
  Website/DesktopModules/Hotcakes/Core/FileUpload.ashx.cs
  Website/DesktopModules/Hotcakes/Core/Scripts/plupload/FileUpload.js
  Website/DesktopModules/Hotcakes/Core/Scripts/plupload/plupload.flash.swf
  Website/DesktopModules/Hotcakes/Core/Scripts/plupload/plupload.full.js
  Website/DesktopModules/Hotcakes/Core/Scripts/plupload/plupload.silverlight.xap
  Website/DesktopModules/Hotcakes/Hotcakes.Modules.csproj
  Website/DesktopModules/Hotcakes/Hotcakes.dnn
  Website/DesktopModules/Hotcakes/ProductViewer/ProductViewerView.ascx.cs
Labels: enhancement

#381 Tasks/header updates
  Build.proj
  Directory.Build.props
  Libraries/Hotcakes.Commerce/Data/EF/HccDbContext.Context.cs
  Libraries/Hotcakes.Commerce/Data/EF/HccDbContext.Designer.cs
  Libraries/Hotcakes.Commerce/Data/EF/HccDbContext.edmx
  Libraries/Hotcakes.Commerce/Data/EF/hcc_OrderPackage.cs
  Libraries/Hotcakes.Commerce/Data/EF/hcc_Variants.cs
  Website/DesktopModules/Hotcakes/Core/HotcakesController.cs
  Website/DesktopModules/Hotcakes/Hotcakes.Modules.csproj
  Website/DesktopModules/Hotcakes/Hotcakes.dnn
  Website/DesktopModules/Hotcakes/Providers/DataProviders/SqlDataProvider/03.06.00.SqlDataProvider
  Website/DesktopModules/Hotcakes/Providers/DataProviders/SqlDataProvider/Uninstall.SqlDataProvider
  Website/DesktopModules/Hotcakes/ReleaseNotes.txt
  build.bat
Labels: enhancement

#382 Release 03.06.00
  Build.proj
  CommonAssemblyInfo.cs
  DevSamples/References/Hotcakes.Commerce.Dnn.dll
  DevSamples/References/Hotcakes.Commerce.dll
  DevSamples/References/Hotcakes.CommerceDTO.dll
  DevSamples/References/Hotcakes.Modules.dll
  DevSamples/References/Hotcakes.Payment.dll
  DevSamples/References/Hotcakes.Web.dll
  GlobalAssemblyInfo.cs
  Website/DesktopModules/Hotcakes/Hotcakes.dnn
  Website/DesktopModules/Hotcakes/Hotcakes_Symbols.dnn
  Website/DesktopModules/Hotcakes/ReleaseNotes.txt
Labels: Task
