Repository HotcakesCommerce/hotcakes-commerce-core, pull requests merged in 2022-10, with the labels that each got.

#413 Fix Installer generated by HCC (BUG)
  Website/DesktopModules/Hotcakes/Hotcakes.dnn
Labels: bug

#388 Get store by cache updates
  Libraries/Hotcakes.Commerce/Accounts/StoreRepository.cs
  Libraries/Hotcakes.Commerce/CacheManager.cs
Labels: enhancement

#392 Add ReadOnly connection string.
  Libraries/Hotcakes.Commerce.Dnn/DnnAffiliateRepository.cs
  Libraries/Hotcakes.Commerce.Dnn/DnnFactory.cs
  Libraries/Hotcakes.Commerce.NoCms/Membership/CustomerAccountRepository.cs
  Libraries/Hotcakes.Commerce/Accounts/StoreRepository.cs
  Libraries/Hotcakes.Commerce/Catalog/BundledProductsRepository.cs
  Libraries/Hotcakes.Commerce/Catalog/CatalogRolesRepository.cs
  Libraries/Hotcakes.Commerce/Catalog/CategoryFacetManager.cs
  Libraries/Hotcakes.Commerce/Catalog/CategoryProductAssociationRepository.cs
  Libraries/Hotcakes.Commerce/Catalog/CategoryRepository.cs
  Libraries/Hotcakes.Commerce/Catalog/GiftCardRepository.cs
  Libraries/Hotcakes.Commerce/Catalog/OptionRepository.cs
  Libraries/Hotcakes.Commerce/Catalog/ProductFileAssociationRepository.cs
  Libraries/Hotcakes.Commerce/Catalog/ProductFileRepository.cs
  Libraries/Hotcakes.Commerce/Catalog/ProductImageRepository.cs
  Libraries/Hotcakes.Commerce/Catalog/ProductInventoryRepository.cs
  Libraries/Hotcakes.Commerce/Catalog/ProductOptionAssociationRepository.cs
  Libraries/Hotcakes.Commerce/Catalog/ProductPropertyRepository.cs
  Libraries/Hotcakes.Commerce/Catalog/ProductPropertyValueRepository.cs
  Libraries/Hotcakes.Commerce/Catalog/ProductRelationshipRepository.cs
  Libraries/Hotcakes.Commerce/Catalog/ProductRepository.cs
  Libraries/Hotcakes.Commerce/Catalog/ProductTypePropertyAssociationRepository.cs
  Libraries/Hotcakes.Commerce/Catalog/VariantRepository.cs
  Libraries/Hotcakes.Commerce/Contacts/AffiliatePaymentRepository.cs
  Libraries/Hotcakes.Commerce/Contacts/AffiliateReferralRepository.cs
  Libraries/Hotcakes.Commerce/Contacts/MailingListRepository.cs
  Libraries/Hotcakes.Commerce/Contacts/ManufacturerRepository.cs
  Libraries/Hotcakes.Commerce/Contacts/VendorRepository.cs
  Libraries/Hotcakes.Commerce/Content/ContentColumnRepository.cs
  Libraries/Hotcakes.Commerce/Content/CustomUrlRepository.cs
  Libraries/Hotcakes.Commerce/Data/HccLocalizationRepoBase.cs
  Libraries/Hotcakes.Commerce/Data/HccRepoBase.cs
  Libraries/Hotcakes.Commerce/Data/HccSimpleRepoBase.cs
  Libraries/Hotcakes.Commerce/Factory.cs
  Libraries/Hotcakes.Commerce/FactoryBase.cs
  Libraries/Hotcakes.Commerce/IFactory.cs
  Libraries/Hotcakes.Commerce/Marketing/PromotionRepository.cs
  Libraries/Hotcakes.Commerce/Membership/UserQuestionRepository.cs
  Libraries/Hotcakes.Commerce/Metrics/SearchQueryRepository.cs
  Libraries/Hotcakes.Commerce/Orders/LineItemRepository.cs
  Libraries/Hotcakes.Commerce/Orders/OrderCouponRepository.cs
  Libraries/Hotcakes.Commerce/Orders/OrderRepository.cs
  Libraries/Hotcakes.Commerce/Orders/OrderTransactionRepository.cs
  Libraries/Hotcakes.Commerce/Orders/RMARepository.cs
  Libraries/Hotcakes.Commerce/Payment/CustomerPointsManager.cs
  Libraries/Hotcakes.Commerce/Reporting/ReportingService.cs
  Libraries/Hotcakes.Commerce/Scheduling/QueuedTaskRepository.cs
  Libraries/Hotcakes.Commerce/Taxes/TaxRepository.cs
  Libraries/Hotcakes.Commerce/WebAppSettings.cs
  Website/DesktopModules/Hotcakes/bin/System.Web.Mvc.dll
  Website/DesktopModules/Hotcakes/bin/System.Web.Mvc.xml
Labels: enhancement, Requires Verification

#414 Update FindManyWithCache Method
  Libraries/Hotcakes.Commerce/Catalog/ProductRepository.cs
Labels: enhancement

#420 Changed-var-key-value-reference
  Website/DesktopModules/Hotcakes/ProductGrid/Settings.ascx.cs
Labels: bug

#422 Updated the Regex method. Issue #421 Fixed
  Libraries/Hotcakes.Web/Validation/ValidationHelper.cs
Labels: bug
