Repository HotcakesCommerce/hotcakes-commerce-core, pull requests merged in 2024-12, with the labels that each got.

#492 Check Store ID when Checking for Duplicate Variants
  Libraries/Hotcakes.Commerce/Catalog/VariantRepository.cs
Labels: bug

#509 Fix Issue 508
  Website/DesktopModules/Hotcakes/Core/Controllers/CheckoutController.cs
Labels: bug, enhancement

#514 HCC: Edit Order > FInd Customer bug
  Website/DesktopModules/Hotcakes/Core/Admin/Orders/App_LocalResources/CreateOrder.aspx.resx
  Website/DesktopModules/Hotcakes/Core/Admin/Orders/CreateOrder.aspx
  Website/DesktopModules/Hotcakes/Core/Admin/Orders/CreateOrder.aspx.cs
Labels: enhancement

#495 Update stripe api
  Libraries/Hotcakes.Payment/CardData.cs
  Libraries/Hotcakes.Payment/Gateways/StripeProcessor.cs
  Website/DesktopModules/Hotcakes/Core/Controllers/CheckoutController.cs
  Website/DesktopModules/Hotcakes/Core/Models/CheckoutViewModel.cs
  Website/Portals/_default/HotcakesViews/Bootstrap4/Scripts/Checkout.js
  Website/Portals/_default/HotcakesViews/Bootstrap4/Views/Checkout/App_LocalResources/Controller.resx
  Website/Portals/_default/HotcakesViews/Bootstrap4/Views/Checkout/_CreditCardInput.cshtml
  Website/Portals/_default/HotcakesViews/Porto5/Scripts/Checkout.js
  Website/Portals/_default/HotcakesViews/Porto5/Views/Checkout/App_LocalResources/Controller.resx
  Website/Portals/_default/HotcakesViews/Porto5/Views/Checkout/_CreditCardInput.cshtml
  Website/Portals/_default/HotcakesViews/SocialSpokes/Scripts/Checkout.js
  Website/Portals/_default/HotcakesViews/SocialSpokes/Views/Checkout/App_LocalResources/Controller.resx
  Website/Portals/_default/HotcakesViews/SocialSpokes/Views/Checkout/_CreditCardInput.cshtml
  Website/Portals/_default/HotcakesViews/_default-Legacy/Scripts/Checkout.js
  Website/Portals/_default/HotcakesViews/_default-Legacy/Views/Checkout/App_LocalResources/Controller.resx
  Website/Portals/_default/HotcakesViews/_default-Legacy/Views/Checkout/_CreditCardInput.cshtml
  Website/Portals/_default/HotcakesViews/_default/Scripts/Checkout.js
  Website/Portals/_default/HotcakesViews/_default/Views/Checkout/App_LocalResources/Controller.resx
  Website/Portals/_default/HotcakesViews/_default/Views/Checkout/_CreditCardInput.cshtml
Labels: bug, enhancement
